r18n/r18n

r18n-desktop/lib/r18n-desktop/win32.rb
DL, which was already deprecated in ruby 2.1.x in Win32, has been removed in ruby 2.2.x. This PR is to replace DL with Fiddle.
=> Replace DL with Fiddle on Win32

r18n-core/lib/r18n-core/i18n.rb
Prevent crashes on requests with Accept-Language header with missing language code.
Real world example (it crashed on "q=0.47,-BE"):
Accept-Language: fr-FR,fr;q=0.97,fr-BE;q=0.93,en-US;q=0.9,en;q=0.87,it-IT;q=0.83,it;q=0.8,nl-NL;q=0.77,nl;q=0.73,de-DE;q=0.7,de;q=0.67,nl-BE;q=0.63,en-GB;q=0.6,de-CH;q=0.57,fr-CH;q=0.53,fr-CA;q=0.5,en-EN;q=0.47,-BE;q=0.43,ru-RU;q=0.4,ru;q=0.37,es-ES;q=0.33,es;q=0.3,en-AU;q=0.27,be-BY;q=0.23,be;q=0.2,bg-BG;q=0.17,bg;q=0.13,fr-FR;q=0.1,en-US;q=0.07
=> Better sanity check for Accept-Language header

r18n-core/ChangeLog.md, r18n-core/lib/r18n-core/i18n.rb, r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/translation.rb, r18n-rails-api/lib/r18n-rails-api/backend.rb
Ruby 2.4 [unified them](https://bugs.ruby-lang.org/issues/12005).
Now we have warnings about that.
Resolve #141
=> Replace all Fixnum and Bignum for Integer

.travis.yml
Support of Ruby 2.1 [has ended](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/).
=> Remove Ruby 2.1 from Travis CI config

r18n-core/lib/r18n-core/translated_string.rb, r18n-core/lib/r18n-core/translation.rb, r18n-core/spec/translation_spec.rb
The subject says it all, this is the fix for issues discussed in #136.
The solution drops the `@value` idea and uses self as the authoritative value again instead, but the trick was to use `super` instead of `self` in `#to_s` to make it all work correctly with `String.new`, ActiveRecord's `StringBuffer`, etc.
Tested against 2.1.10, 2.2.3, 2.3.4 and 2.4.1.
BTW, note that I kept the changes at the minimum, so `Untranslated#to_s` still returns `TranslatedString`, not `String`, as it always did before. I am not sure if this was intentional or not. If you want to change this, simply adding `.to_s` on the `@filter.process` result in `Untranslated#to_s` would do the trick.
=> Fix for TranslatedString to close #136

Rakefile, benchmark/benchmark.rb, r18n-core/Rakefile, r18n-desktop/Rakefile, r18n-rails-api/Rakefile, r18n-rails/spec/app/config/boot.rb, sinatra-r18n/Rakefile
They aren't necessary:
http://www.rubyinside.com/why-using-require-rubygems-is-wrong-1478.html
https://github.com/rails/rails/commit/d8c194968469f3afe39412818505ac94f78e386d#diff-64230db87218c6b7c92fb9b6c4436c46
Fewer lines of code to maintain 😊
=> Remove rubygems requires

r18n-core/lib/r18n-core/translated_string.rb, r18n-core/spec/translation_spec.rb
Calling `to_s` will only return an html safe string if the `html_safe` method is defined, so `html_safe?` should match that behaviour. The existing implementation creates vulnerabilities in environments where `html_safe` is not defined and objects that return true for `html_safe?` are not escaped.
=> Fix TranslatedString#html_safe? always returning true

r18n-core/locales/en-gb.rb, r18n-core/locales/en.rb
There is no warranty that base `en` will not be showed for US users with another format.
In Ruby on Rails:
* [en](https://github.com/svenfuchs/rails-i18n/blob/fe07d45/rails/locale/en.yml#L42)
* [en-US](https://github.com/svenfuchs/rails-i18n/blob/fe07d45/rails/locale/en-US.yml#L42)
* [en-GB](https://github.com/svenfuchs/rails-i18n/blob/fe07d45/rails/locale/en-GB.yml#L42)
=> Make `date_format` of base `en` locale international

README.md, r18n-core/README.md, r18n-desktop/README.md, r18n-rails/README.md
=> Fix code examples in READMEs after date format changing for `en` locale

r18n-core/lib/r18n-core/locale.rb, r18n-core/spec/locale_spec.rb
```ruby
DateTime.now.is_a?(Date) # => true
```
But this type also has time information.
=> Fix `Locale#localize` method for `DateTime` objects

r18n-core/lib/r18n-core/untranslated.rb
As I have mentioned this issue in #147 already, it returned `TranslatedString` before. This often made code which uses localized strings work when the strings were translated but break when they were not translated. For example, something like
``` ruby
puts "foo".gsub("x", t.some.string)
```
worked when `t.some.string` was translated but crashed when it was not, even if the localized string itself is not used as such in this case.
As we have been recently bitten by this issue again, I thought it might be a good idea to have it fixed. It goes without saying that I have made sure that all the specs still work in all the tested rubies as well. If we could eventually get a release with this included, it would be great. Thanks.
=> Make sure Untranslated#to_s returns String as expected.

r18n-core/lib/r18n-core/filter_list.rb, r18n-core/spec/filters_spec.rb
... from `TranslatedString`, which initialized without `filters` from `FilterList`.
-----
It's very critical old bug. I've spend around 1 hour to find this. I'm very sad that `r18n-core` have no unit specs for `TranslatedString`, `FilterList` and `Untranslated`.
=> Fix bug with `Untranslated#to_s`, when it initialized without `filters`

r18n-desktop/lib/r18n-desktop.rb, r18n-desktop/spec/i18n/en.yml, r18n-desktop/spec/r18n-desktop_spec.rb
The specific for `r18n-desktop` method `R18n.from_env` didn't use (set) `R18n.default_places`, which used by other adapters (`sinatra-r18n`, for example).
Resolve #151 
@bodrovis, can you please check?
=> Fix `R18n.set` for `r18n-desktop`

r18n-core/lib/r18n-core/translation.rb, r18n-core/spec/translation_spec.rb, r18n-core/spec/translations/general/en.yml
I think we don't need for `Kernel#itself` implementation.
If you don't agree — please, open an issue or create a PR.
=> Redefine `Translation#itself` method as key

r18n-core/spec/locale_spec.rb
https://docs.ruby-lang.org/en/2.5.0/NEWS.html#label-Stdlib+updates+-28outstanding+ones+only-29
=> Fix warning about `BigDecimal` initialization

r18n-core/lib/r18n-core/locale.rb, r18n-core/spec/locale_spec.rb
`DateTime - Time.now` (default) gives `TypeError (expected numeric)`.
=> Fix `Locale#format_time_human` for `DateTime`

r18n-core/lib/r18n-core/translated_string.rb, r18n-core/spec/translation_spec.rb
=> Fix `TranslatedString#to_ary`, don't return Untranslated

r18n-core/lib/r18n-core/translated_string.rb
=> Remove duplicating `reposnd_to? :html_safe` in `TranslatedString`

r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/utils.rb, r18n-core/spec/locale_spec.rb
You can just define `R18n::Locale#format_{underscored_class_name}_{format}` method
for this in your projects, like `#format_foo_bar_human`.
---
@ai, what do you think? It requires an additional (the first for `r18n-core`) dependency, because Ruby (stdlib) still has no `String#underscore` method.
It can be `ActiveSupport`, but I like mine gem with refinements (namespace patching instead of global).
There is can be another alternative, or requirement for methods with names like `#format_FooBar_human`.
=> Add support for custom classes localizing (`R18n.l`)

r18n-core/lib/r18n-core/untranslated.rb, r18n-core/spec/translation_spec.rb
For methods with double-splat, as in Cucumber.
Resolve #191
=> Fix `TranslatedString#to_hash`

README.md, r18n-core/README.md, r18n-core/lib/r18n-core/yaml_loader.rb, r18n-core/spec/r18n_spec.rb, r18n-core/spec/translations/yaml/en-GB.yml, r18n-core/spec/translations/yaml/en-us.yml, r18n-core/spec/yaml_loader_spec.rb
`en-US.yml`, for example, along with `en-us.yml`.
=> Allow upcased region in translation file names

r18n-core/lib/r18n-core/i18n.rb, r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/yaml_loader.rb, r18n-core/spec/i18n_spec.rb, r18n-core/spec/locales/en-us_spec.rb
For example, load `en` base translations for `en-US` locale,
when `en` is unavailable in the directory with translation.
=> Load `base` translations from parent locale

r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/translated.rb, r18n-core/lib/r18n-core/unsupported_locale.rb, r18n-core/spec/translated_spec.rb
Example: `Object#name_en_us` instead of `#name_en-US`.
Method names with `-` has problems with literal (you have to use `public_send`)
and something in Shrine gem (`eval`, I guess).
=> Downcase locales with regions for `Translated`

.cirrus.yml, .rubocop.yml, r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/locales/hu.rb, r18n-core/lib/r18n-core/version.rb, r18n-core/lib/r18n-core/yaml_loader.rb
https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/
=> Drop Ruby 2.3 support

r18n-core/lib/r18n-core/locale.rb, r18n-core/lib/r18n-core/locales/af.rb, r18n-core/lib/r18n-core/locales/az.rb, r18n-core/lib/r18n-core/locales/en-us.rb, r18n-core/lib/r18n-core/locales/es-us.rb, r18n-core/lib/r18n-core/locales/fi.rb, r18n-core/lib/r18n-core/locales/hu.rb, r18n-core/lib/r18n-core/locales/tr.rb, r18n-core/lib/r18n-core/locales/vi.rb, r18n-core/spec/i18n_spec.rb, r18n-core/spec/locales/af_spec.rb, r18n-core/spec/locales/en-us_spec.rb, r18n-core/spec/locales/es-us_spec.rb, r18n-core/spec/locales/fi_spec.rb, r18n-core/spec/locales/hu_spec.rb, r18n-core/spec/locales/vi_spec.rb
Example: `l Time.now, :standard, with_seconds: true # => '05.06.2019 13:31:42'`
=> Add `:with_seconds` option for Time formatting

r18n-core/lib/r18n-core/locales/id.rb, r18n-core/spec/locales/id_spec.rb
Hi,
I want to add a couple improvements for Indonesian translation:
- Change 'Nopember' to 'November' ([it's the correct spelling](https://id.wikipedia.org/wiki/November)).
- Update time format to use dots as separator.
- Add tests.
=> Improve Indonesian translation

r18n-core/lib/r18n-core/i18n.rb, r18n-core/spec/i18n_spec.rb, r18n-core/spec/yaml_loader_spec.rb
For example, if project has `en-US` and `de-DE` locales, and `Accept-Language` header contains only `de` — set `de-DE` as locale.
=> Set `I18n#locale` with region by its parent equal to received locale

r18n-core/lib/r18n-core/filters.rb, r18n-core/spec/filters_spec.rb, r18n-core/spec/translations/general/en.yml
It will force Symbol keys, but it does not break specs
and it's more flexible.
=> Allow Hashes with blocks for `named_variables` filter

r18n-core/lib/r18n-core.rb, r18n-core/spec/r18n_spec.rb
I don't know why (for what) they were here,
they were introduced in d14728cb3ec615d28b90e041000583a93df38dd1
without any description.
I see no profit from such approach.
Use regular `set` or justify the necessity, please.
=> Remove block setters
